version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: dnd-mongodb
    ports:
      - "28017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dnd_character_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Backend service
  backend:
    image: punked/dnd-charactersheetapp-backend:latest
    build: ./backend
    container_name: dnd-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./data/5etools-v2.10.2/data:/app/data:ro
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DND_DATA_PATH=/app/data

  # Frontend service
  frontend:
    image: punked/dnd-charactersheetapp-frontend:latest
    build: ./frontend
    container_name: dnd-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://localhost:8000

# Volumes for data persistence
volumes:
  mongodb_data: